import localFont from "next/font/local";
import "./globals.css";
import SideBar from "./components/common/SideBar";
import ClientLayout from "./components/clientLayout/ClientLayout"; // client component

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="dark">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="flex max-w-7xl m-auto">
          <SideBar />
          <ClientLayout>{children}</ClientLayout>
        </div>
      </body>
    </html>
  );
}
